{
 "title": "Pipeline: Gardener",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project",
    "query": "mlab-sandbox,mlab-staging,mlab-oti"
   },
   { "name": "pipelineDatasource", "label": "Data Processing", "query": "prometheus" },
   { "name": "prometheusDatasource", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "deployment",
    "label": "Gardener Deployment",
    "query": "label_values(up{deployment=~\"etl-gardener-.*\"}, deployment)"
   }
  ]
 },
 "panels": [
  {
   "title": "Reprocessing Period",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Days" }
   ],
   "targets": [
    {
     "expr": "bq_gardener_parse_time_difference_days",
     "legendFormat": "{{dataset}}"
    }
   ]
  },
  {
   "title": "Hourly Warning and Failure Rates",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "3600 * rate(gardener_warning_total{container=\"etl-gardener\", deployment=~\"$deployment\"}[1h])",
     "legendFormat": "Warning: {{status}}"
    },
    {
     "expr": "3600 * rate(gardener_fail_total{container=\"etl-gardener\", deployment=~\"$deployment\"}[1h])",
     "legendFormat": "Failure: {{status}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{container=\"etl-gardener\", deployment=~\"$deployment\"}[5m])",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "GoRoutine Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{container=\"etl-gardener\", deployment=~\"$deployment\"}",
     "legendFormat": "{{deployment}}"
    },
    {}
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{container=\"etl-gardener\", deployment=~\"$deployment\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Tasks In Flight",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gardener_tasks_in_flight{deployment=~\"$deployment\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Time in State (95th Percentile)",
   "type": "graph",
   "description": "How long each date spends in each processing state.\nIf Processing exceeds 12 hours, then there will likely be data loss from expiration in the task queue.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(gardener_state_time_histogram_bucket{deployment=~\"$deployment\"}[1h])) by (deployment, state, le))",
     "legendFormat": "{{state}} {{deployment}}"
    }
   ]
  },
  {
   "title": "Start and Completion Rate (hourly)",
   "type": "graph",
   "description": "Number of tasks started and completed, per hour.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Tasks / Hour" }
   ],
   "targets": [
    {
     "expr": "sum by(deployment) (increase(gardener_started_total{deployment=~\"$deployment\"}[1h]))",
     "legendFormat": "Started {{deployment}}"
    },
    {
     "expr": "sum by(deployment) (-increase(gardener_completed_total{deployment=~\"$deployment\"}[1h]))",
     "legendFormat": "Completed {{deployment}}"
    }
   ]
  },
  {
   "title": "SLO: Completion Rate (Tasks / day)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Tasks / Day" }
   ],
   "targets": [
    {
     "expr": "sum by(deployment) (increase(gardener_completed_total{deployment=~\"$deployment\"}[24h]))",
     "legendFormat": "Completed {{deployment}}"
    }
   ]
  },
  {
   "title": "Empty TQ Stats Resolution Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes / File" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, avg(gardener_empty_stats_recovery_sec) by (version, status, le))",
     "legendFormat": "{{status}} {{version}}"
    }
   ]
  },
  {
   "title": "Task Date of Recent State Updates",
   "type": "graph",
   "description": "Task dates of the most recent updates to each task state.\n\nNOTE: In sandbox, we now process only a small subset of the requests, to get high throughput and test across the full date range quickly.  Cycle time is less than a day for sandbox, compared with one or two weeks for production.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "dateTimeAsIso", "label": "State update for task date" }
   ],
   "targets": [
    {
     "expr": "1000*quantile_over_time(0.2, gardener_state_date{deployment=~\"$deployment\"}[20m])",
     "legendFormat": "{{deployment}} {{state}}"
    }
   ]
  },
  {
   "title": "Byte Rate",
   "type": "graph",
   "description": "This measures the bytes submitted for processing. \n It reflects the ETL throughput, which is governed by the task queue rate and concurrency settings.\n\nThe rate is governed by how fast the ETL pipeline drains the task queues.  The balance across types is governed by the rate/concurrency settings on the queues.\n\nThis is fundamentally rather lumpy at the 10 minute level, so we average over an hour or more.  Aside from the fine-grained lumpiness, this should be the most stable of the throughput metrics, because it reflects the quantity of data, rather than the number or size of files.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes/Hour" }
   ],
   "targets": [
    {
     "expr": "sum by(deployment, year)(rate(gardener_bytes_sum{deployment=~\"$deployment\"}[1h])*3600)",
     "legendFormat": "{{deployment}} {{year}}"
    }
   ]
  },
  {
   "title": "File Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Files / Hour" }
   ],
   "targets": [
    {
     "expr": "sum by(deployment, year)(rate(gardener_files_sum{deployment=~\"$deployment\"}[1h])*3600)",
     "legendFormat": "{{deployment}} {{year}}"
    }
   ]
  },
  {
   "title": "Bytes / File",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes / File" }
   ],
   "targets": [
    {
     "expr": "avg by(deployment, year) (\n    rate(gardener_bytes_sum{deployment=~\"$deployment\"}[1h]) /\n    rate(gardener_files_sum{deployment=~\"$deployment\"}[1h]))",
     "legendFormat": "{{deployment}} {{year}}"
    }
   ]
  }
 ]
}